version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Chinhpro123a"
      MSSQL_PID: Express
    ports:
      - "11433:1433"
  myapi:
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"
