version: '3'
services:
  ms-sql-server:
    image: nineh/quanlyd
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Supercoolpassword123!"
      MSSQL_PID: Express
    ports:
      - "11433:1433"
  myapi:
    image: nineh/quanly
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "7145:80"
