version: '3'
services:
  ms-sql-server:
    image: restored-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Supercoolpassword123!"
      MSSQL_PID: Express
    ports:
      - "11433:1433"
  myapi:
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"
